### ISSUE TITLE
Missing bindings for PangoGravity functions

### ISSUE THREAD

**Issue by federicomenaquintero** [gtk-rs/pango#156]
`pango_gravity_to_rotation` doesn't have a binding; this one should just look like a method.

The following are missing bindings, too, but they *return* a PangoGravity:  `pango_gravity_get_for_matrix`, `pango_gravity_get_for_script`, `pango_gravity_get_for_script_and_width`.

**Comment by GuillaumeGomez** [comment]
\*Normally\* I added almost everything. So if not there, either it's new or there was an issue with adding it. I'll take another look.

**Comment by EPashkin** [comment]
Its because `PangoGravity` is enum and gir currently don't generate functions for it.

**Comment by GuillaumeGomez** [comment]
Thanks @EPashkin ! So it'll require manual binding (and maybe try to fix it in gir as well?).
