### ISSUE TITLE
Update pango bindings

### ISSUE THREAD

**Issue by ford-prefect** [gtk-rs/pango#165]
Pango 1.44 has been around since end July, so would be good to get updated bindings.

**Comment by GuillaumeGomez** [comment]
Indeed! Like said on IRC, I'll add it in the next days if no one did before.

**Comment by sdroege** [comment]
Should also update the gir files of the other things at the same time to the corresponding releases though :)

**Comment by GuillaumeGomez** [comment]
Good point.

**Comment by sdroege** [comment]
You updated to the eoan Ubuntu versions but that's only Pango 1.42 :)

**Comment by GuillaumeGomez** [comment]
I can look for other sources...

**Comment by GuillaumeGomez** [comment]
We even have generated for the 1.46 now so closing.
