### ISSUE TITLE
need an enum for the PangoScale values

### ISSUE THREAD

**Issue by emmanueltouzery** [gtk-rs/pango#193]
the original values are there:
https://developer.gnome.org/pango/stable/pango-Text-Attributes.html#PANGO-SCALE-X-LARGE:CAPS

They are #defined in pango. I believe they're needed to build a GtkTextTag with a specific size, as in the gtk3 demo:

```c
  gtk_text_buffer_create_tag (buffer, "big",
                              /* points times the PANGO_SCALE factor */
                              "size", 20 * PANGO_SCALE, NULL);

  gtk_text_buffer_create_tag (buffer, "xx-small",
                              "scale", PANGO_SCALE_XX_SMALL, NULL);

  gtk_text_buffer_create_tag (buffer, "x-large",
                              "scale", PANGO_SCALE_X_LARGE, NULL);
```

I'm not really sure it should be an enum though, because the first example there seems to do arithmetic with the value (20*PANGO_SCALE).

**Comment by sdroege** [comment]
They should be constants in the bindings, or maybe we need a `Scale` type that also implements arithmetic operations but that would be a second step.

**Comment by EPashkin** [comment]
There no PANGO_SCALE_ in Pango-1.0.gir so in need be added manually

**Comment by emmanueltouzery** [comment]
i'm sorry i think the arithmetic is probably not needed. The first case that does arithmetic populates the "size". When "scale" is populated the values are directly put in. I think PANGO_SCALE is something else than PANGO_SCALE_*

**Comment by sdroege** [comment]
`PANGO_SCALE` is a scaling constant, IIRC it's the value "1.0" for the fixed point pango scale. The `PANGO_SCALE_XXX` constants are constants for specific values

**Comment by sdroege** [comment]
@emmanueltouzery Do you want to create a PR for adding such constants?

**Comment by emmanueltouzery** [comment]
Ok, I'll try to prepare a PR ASAP (might take me a little time)
