### ISSUE TITLE
Does not include cairo backend rendering.

### ISSUE THREAD

**Issue by withoutboats** [gtk-rs/pango#31]
`pango/pangocairo.h` includes a number of functions for rendering text with pango to cairo surfaces. Rust bindings for these functions are missing from `pango/pango::ffi` and `sys/pango-sys`.

**Comment by GuillaumeGomez** [comment]
What is the object/functions which missing more precisely please ?

**Comment by withoutboats** [comment]
Everything documented [here](https://developer.gnome.org/pango/stable/pango-Cairo-Rendering.html#pango-cairo-create-context).

**Comment by gkoz** [comment]
Looks like adding those will require some fixes for the generator.

**Comment by GuillaumeGomez** [comment]
@gkoz: I was about to ask you about this. :)

**Comment by LaylConway** [comment]
Is there an update on this? These are fairly important for games that want to use cairo and pango as a rendering backend for UI systems

**Comment by GuillaumeGomez** [comment]
Nothing for the moment.

cc @gkoz @EPashkin

**Comment by EPashkin** [comment]
Note: There separate library by @RazrFalcon https://crates.io/crates/pangocairo
