### ISSUE TITLE
Remove the Option return type for all types creation

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/pango#5]
Remove the Option return type for all types creation and replace it by an assert or something like it.

**Comment by gkoz** [comment]
I'm hacking on another iteration of the object wrappers reform. Before that is either ready or abandoned refactoring all constructors might be counterproductive.

**Comment by GuillaumeGomez** [comment]
I didn't intend to start it right away. We have other problems to solve before.
