### ISSUE TITLE
 PangoAttribute support

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/pango#80]
Looks like [Text Attributes](https://developer.gnome.org/pango/stable/pango-Text-Attributes.html) doesn't implemented at all. Does it easily implemented?

Personally, I need only `pango_attr_underline_new`, `pango_attr_letter_spacing_new` and `pango_attr_strikethrough_new`.

**Comment by GuillaumeGomez** [comment]
It cannot be generated automatically, so manual binding required.

**Comment by RazrFalcon** [comment]
Is it hard to do? From where can I start?

**Comment by GuillaumeGomez** [comment]
It might be a bit tricky. The issue starts [here](https://developer.gnome.org/pango/stable/pango-Text-Attributes.html#pango-attribute-init) because of the [AttrClass](https://developer.gnome.org/pango/stable/pango-Text-Attributes.html#PangoAttrClass). Once AttrClass is done, it should be quick.

**Comment by RazrFalcon** [comment]
Does `AttrClass` can be autogenerated?

**Comment by GuillaumeGomez** [comment]
Nope, that's the problem.

**Comment by GuillaumeGomez** [comment]
If you're not too much into a hurry, I might be able to do it in the next hours after I'm done with my current task.

**Comment by RazrFalcon** [comment]
Well, if it takes less that a month - i'm fine =)

**Comment by GuillaumeGomez** [comment]
For the published crate, it might take a month. :D

But you'll be able to use the repository directly.

**Comment by RazrFalcon** [comment]
Yep. git is fine for now.

**Comment by GuillaumeGomez** [comment]
Ok, once #82 is merged, you'll have everything you need and even more.

**Comment by RazrFalcon** [comment]
Thanks, but I can't figure out how to use it. I have:
```rust
let attr = pango::functions::attr_underline_new(pango::Underline::Single);
```

And now I have to insert it to the attributes list, which should look like:
```c
    PangoAttrList *attr_list = pango_attr_list_new();
    
    PangoAttribute *attribute = pango_attr_underline_new(PANGO_UNDERLINE_SINGLE);
    attribute->start_index = 0;
    attribute->end_index = -1;
    pango_attr_list_insert(attr_list, attribute);

    pango_layout_set_attributes(layout, attr_list);
    pango_attr_list_unref(attr_list);
```

But none of these methods are implemented.

**Comment by EPashkin** [comment]
It different from that you say on start issue ;)
When `AttrList` added to generation, gir generate all needed functions (with need some `const` fixes).
Only need add manual setters for attribute fields to https://github.com/gtk-rs/pango/blob/master/src/attribute.rs.

**Comment by EPashkin** [comment]
Hm. Seems `pango_attr_list_insert` and 3 others maybe need some manual implementation if don't works after `const`-configure.

**Comment by RazrFalcon** [comment]
>It different from that you say on start issue

I agree, but why I need `Attr` creating without using it =)

>Only need add manual setters for attribute fields

But `pango_layout_set_attributes` is still commented out.

**Comment by EPashkin** [comment]
It will be uncommented after generating `AttrList`

**Comment by GuillaumeGomez** [comment]
Yes please. And this time specify *everything* you need. :)
