### ISSUE TITLE
Add text style attributes support

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/pango#83]
We need at least:
- [ ] `pango_attr_list_new`
- [ ] `pango_attr_list_insert`
- [ ] `pango_layout_set_attributes`

**Comment by EPashkin** [comment]
This can be done with just generating Pango.AttrList,
By https://github.com/gtk-rs/pango/issues/80#issuecomment-313666391 seems you also need setters\getters for Attribute properties?

**Comment by RazrFalcon** [comment]
Probably. I don't know what default values is for `start_index` and `end_index`, but currently I need `0` and `-1` accordingly.

**Comment by RazrFalcon** [comment]
Looks like this properties is ok by default: https://developer.gnome.org/pango/stable/pango-Text-Attributes.html#PangoAttribute

> By default an attribute will have an all-inclusive range of [0,G_MAXUINT].

**Comment by EPashkin** [comment]
I try generate it (with manual setters)
